version: "3.9"

services:
  wordpress:
    image: wordpress:6.8.3-php8.1
    container_name: avatarsteward_wordpress
    restart: unless-stopped
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    volumes:
      # Plugin principal: montar desde la raíz (incluye avatar-steward.php, src/, assets/)
      - ./:/var/www/html/wp-content/plugins/avatar-steward
      # Subdirectorios específicos de wp-content (para evitar conflictos)
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/languages:/var/www/html/wp-content/languages
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      # Configuración de WordPress
      - ./docker/config/wp-config.php:/var/www/html/wp-config.php:ro
      # Logs de Apache/PHP para inspección en tiempo real
      - ./docker_logs:/var/log/apache2
      # Volumen persistente para WordPress core
      - wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: avatarsteward_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    container_name: avatarsteward_phpmyadmin
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

volumes:
  wordpress_data:
  db_data:
